### ISSUE TITLE
[Feature] Hide/Remove "Recommended For You"

### ISSUE THREAD

**Issue by MadMakz** [LinogeFly/hide-unwanted-streams-on-twitch#11]
Since Twitch still lacks an option for disableing this it would be nice to have an option to hide the whole "Recommended For You" thing.

Many people asked for it on Reddit already.
https://www.reddit.com/r/Twitch/comments/47ucfe/anyway_to_disable_the_annoying_recommended_for/
https://www.reddit.com/r/Twitch/comments/47ucfe/anyway_to_disable_the_annoying_recommended_for/

 I'm old and informed enough to know about what i want to follow and whatnot by myself and i do not or do not want to subscribe to categories anyway.

`.js-recommended-games {display: none !important;}` should do the trick.

**Comment by LinogeFly** [comment]
Hi,
Thanks for your suggestion. Didn't know that "Recommended For You" section bugs other people :). Yes, I think I'm gonna do that. I will add option in the settings to hide that section on Twitch. That "Recommended For You" section is only on "Games" page currently, right?

**Comment by MadMakz** [comment]
> That "Recommended For You" section is only on "Games" page currently, right?

Correct :)

**Comment by LinogeFly** [comment]
Hm, is it me or "Recommended For You" section is not there anymore? Looks like Twitch has removed that thing themselves :)

**Comment by LinogeFly** [comment]
No, it's visible. Weird... at work I opened Twitch and that "Recommended For You" was not there. Now it's visible when I open Twitch at home.

**Comment by MadMakz** [comment]
Maybe another hiccup? As you might know, Twitchs API/Javascript isn't really the elite thing on the web :D

**Comment by LinogeFly** [comment]
There is one problem that I didn't see right away regarding that "Recommended For You" section. It's not a technical problem but kind or usability problem. I will explain.

The thing is that games on Directory page are either in "All Games" section or in "Recommended For You" section. So if I hide whole "Recommended For You" section games that Twitch recommends to me will not be visible anywhere on Directory page. I can see a confusion in that for users. Of course you can go to a game page you are interested in with direct link or from "Followed Games" menu or in some other way. But still I find such option to be confusing.

So I'm sorry but I'm not gonna add an option to hide "Recommended For You" section in the extension. But what I will do to help you and others regarding this issue is make simple script/extension that specifically removes "Recommended For You" section on Twitch. I will share it here when it's done. It's gonna work in a similar way as this extension. You install it into your browser and "Recommended For You" will be hidden for you on Directory page.

**Comment by LinogeFly** [comment]
[Here is](https://openuserjs.org/scripts/LinogeFly/Twitch_Recommended_For_You_Remover) the script I wrote about earlier that disables "Recommended For You" section. You can use it with Chrome or Firefox. There is a description on how to install in "Installation" section. Let me know how it works for you.
